apiVersion: v1
entries:
  zookeeper:
  - apiVersion: v1
    created: "2026-01-11T18:45:31.3986076+02:00"
    description: Centralized service for maintaining configuration information, naming,
      providing distributed synchronization, and providing group services.
    digest: 544f8fc17ab875ced024b89c64a3b158dd61b7a283f45d5bfad293f57b32cbb4
    home: https://zookeeper.apache.org/
    icon: https://zookeeper.apache.org/images/zookeeper_small.gif
    maintainers:
    - email: lachlan@deis.com
      name: Lachlan Evenson
    - email: owensk@google.com
      name: Kenneth Owens
    name: zookeeper
    sources:
    - https://github.com/apache/zookeeper
    - https://github.com/kubernetes-zookeeper/kubernetes-zookeeper
    urls:
    - https://kubernetes-zookeeper.github.io/kubernetes-zookeeper/helm/repo/zookeeper-1.0.tgz
    version: "1.3"
generated: "2026-01-11T18:45:31.3967824+02:00"
